# 数据源配置
spring:
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      bigdataplat:
        # 主库数据源
        one:
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://110.110.1.56:3306/bigdataplat?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: sql@zzq!123
      bigdataplatsqlserver:
        # 主库数据源
        one:
          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://110.110.1.109:1433;DatabaseName=bigdataplat
          username: sa
          password: 198603yang
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: zzq
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true


  # redis 配置
  redis:
    # 地址
    host: 110.110.1.26
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: zzq2017
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

dubbo:
  application:
    name: bigdataplat-application-dubbo-provider
    owner: dev
  monitor:
    protocol: registry
  provider:
    timeout: 15000
  protocol:
    heartbeat: 60000
    port: 20887
    threadpool: limited
    threads: 6000
  registry:
    address: zookeeper://110.110.1.230:2182

